// HERO: a live policy circuit, tracing a budget choice through time.
let labTimer=null,labFocus=0,labStep=1,labDraft=null,labRows=null,labBase=null;
const LAB_NOTES=[
 ['Your policy lever','Annual spending is an input, in starting-year £bn. The slider previews an additional change on top of your current plan. Apply commits both the spending and its funding.'],
 ['Every pound has a source','Transfers and tax increases close the initial funding gap. Borrowing leaves services and taxes unchanged initially. Later inflation, demographics and tax feedback can change that balance.'],
 ['Demand, then supply','The model applies temporary fiscal multipliers to the level of GDP. Its inflation response and delayed health/investment effects are assumptions. These links are mechanisms in this model, not proven causal estimates.'],
 ['The debt feedback','Annual borrowing adds to the debt stock. Interest depends on outstanding debt and gradual refinancing. Market yields are editable assumptions; extra borrowing does not automatically change Bank Rate.']
];
function stopLab(){clearInterval(labTimer);labTimer=null;if($('#labPlay'))$('#labPlay').textContent='▶ Play';}
function renderExplorer(){
 stopLab();labStep=1;labFocus=0;labDraft=null;
 const el=$('#economicExplorer');if(!el)return;
 el.innerHTML=`<div class="explorer-head"><div><div class="eyebrow"><span class="live-dot"></span> INTERACTIVE POLICY LAB</div><h2>Follow the money. Watch the consequences.</h2><p>Move a lever. Trace the model. Scrub through the years.</p></div><button id="labCollapse" aria-expanded="true">Collapse lab −</button></div><div id="labBody"><div class="lab-toolbar"><div><label for="labSector">01 / Change a service</label><select id="labSector">${SECTORS.filter(([k])=>k!=='residual').map(([k,n])=>`<option value="${k}" ${k==='defence'?'selected':''}>${esc(n)}</option>`).join('')}</select></div><div class="lab-lever"><label for="labAmount">Additional annual spending <output id="labAmountText">£0bn</output></label><input id="labAmount" type="range" min="-50" max="100" step="1" value="0"><span>−£50bn <span>drag to experiment</span> +£100bn</span></div><div><label for="labRoute">02 / Fund it</label><select id="labRoute"><option value="borrow">Borrow / reduce borrowing</option><option value="sector">Transfer with a service</option><option value="equal">Share across services</option><option value="tax">Adjust tax receipts</option></select></div><div id="labSourceWrap"></div><button id="labApply" class="primary">Apply to budget</button></div><div id="labError" role="status"></div><div class="circuit-scroll"><div class="circuit"><svg class="circuit-wires" viewBox="0 0 1200 220" preserveAspectRatio="none" aria-hidden="true">${[0,1,2].map(n=>`<path class="wire" data-wire="${n}" d="M${230+n*300},108 C${280+n*300},108 ${280+n*300},108 ${320+n*300},108"/><path class="pulse" data-wire="${n}" d="M${230+n*300},108 C${280+n*300},108 ${280+n*300},108 ${320+n*300},108"/>`).join('')}</svg><div id="labNodes" class="circuit-nodes"></div></div></div><div class="lab-bottom"><div class="lab-inspector" id="labInspector" aria-live="polite"></div><div class="lab-time"><div class="time-title"><span>SIMULATION YEAR</span><strong id="labYear"></strong></div><div class="time-controls"><button id="labBack" aria-label="Previous simulation year">←</button><button id="labPlay">▶ Play</button><button id="labNext" aria-label="Next simulation year">→</button><select id="labSpeed" aria-label="Playback speed"><option value="900">1×</option><option value="350">3×</option></select></div><input id="labTime" type="range" min="0" max="${horizon}" value="1" aria-label="Simulation year"><div class="time-scale"><span>${year}</span><span>${year+horizon}</span></div><div id="labSpark"></div></div></div><div class="lab-foot"><span><i class="draft-dot"></i> <span id="labStatus">Current plan · drag a lever to preview</span></span><span>Illustrative links · values from the model · <button id="labMethods">Methods ↗</button></span></div></div>`;
 const sector=$('#labSector'),route=$('#labRoute');
 function sourceOptions(){const mode=route.value;$('#labSourceWrap').innerHTML=mode==='sector'?`<label for="labSource">Other service</label><select id="labSource">${SECTORS.filter(([k])=>k!==sector.value&&k!=='residual').map(([k,n])=>`<option value="${k}" ${k==='education'?'selected':''}>${esc(n)}</option>`).join('')}</select>`:mode==='tax'?`<label for="labSource">Receipt category</label><select id="labSource">${inputs(datum(),policy).revenues.filter(t=>!t.id.startsWith('custom')).map(t=>`<option value="${t.id}">${esc(shortName(t.name))}</option>`).join('')}</select>`:'';if($('#labSource'))$('#labSource').onchange=calculate;calculate();}
 function calculate(){stopLab();const amount=Number($('#labAmount').value);$('#labAmountText').textContent=signed(amount);try{labDraft=fundingTransaction(datum(),policy,sector.value,(policy.spend[sector.value]||0)+amount,route.value,$('#labSource')?.value);labRows=simulate(datum(),labDraft.next,settings,horizon);labBase=simulate(datum(),policy,settings,horizon);$('#labError').textContent='';$('#labApply').disabled=!amount;$('#labStatus').textContent=amount?'Preview only · compared with your current plan':'Current plan · drag a lever to preview';drawLab();}catch(e){labDraft=null;labRows=null;$('#labNodes').innerHTML='<div class="invalid-circuit">This scenario cannot be funded as chosen.<br>Reduce the amount or choose another source.</div>';$('#labInspector').textContent='No projection shown for invalid inputs.';$('#labSpark').innerHTML='';$('#labError').textContent=e.message;$('#labApply').disabled=true;}}
 sector.onchange=sourceOptions;route.onchange=sourceOptions;$('#labAmount').oninput=calculate;
 $('#labApply').onclick=()=>{if(!labDraft)return;const tx=labDraft.transaction;policy={...labDraft.next,funding:[...(policy.funding||[]),tx]};result=null;baseline=null;render();toast('Preview applied to your budget');};
 $('#labTime').oninput=e=>{stopLab();labStep=+e.target.value;drawLab();};
 $('#labBack').onclick=()=>{stopLab();labStep=Math.max(0,labStep-1);drawLab();};$('#labNext').onclick=()=>{stopLab();labStep=Math.min(horizon,labStep+1);drawLab();};
 $('#labPlay').onclick=()=>{if(labTimer){stopLab();return;}if(!labRows)return;if(labStep>=horizon)labStep=0;$('#labPlay').textContent='Ⅱ Pause';labTimer=setInterval(()=>{if(!labRows||!$('#labTime')||view!=='budget'){stopLab();return;}labStep++;drawLab();if(labStep>=horizon)stopLab();},+$('#labSpeed').value);};$('#labSpeed').onchange=stopLab;
 $('#labMethods').onclick=methodsInfo;$('#labCollapse').onclick=()=>{const open=!$('#labBody').hidden;$('#labBody').hidden=open;$('#labCollapse').setAttribute('aria-expanded',String(!open));$('#labCollapse').textContent=open?'Open lab +':'Collapse lab −';if(open)stopLab();};sourceOptions();
}
function drawLab(){if(!labRows)return;const r=labRows[labStep],b=labBase[labStep],tx=labDraft.transaction;const gap=sum(Object.values(tx.spend))-sum(Object.values(tx.tax));const tax=sum(Object.values(tx.tax)),cuts=-sum(Object.entries(tx.spend).filter(([k])=>k!==tx.id).map(([,v])=>v));
 const cards=[['01','POLICY',SECTORS.find(s=>s[0]===tx.id)[1],signed(tx.amount),'annual change',`Total ${cash(inputs(datum(),labDraft.next).spending[tx.id])}`],['02','FUNDING',tx.mode==='borrow'?'Debt financing':tx.mode==='tax'?shortName(inputs(datum(),policy).revenues.find(t=>t.id===tx.source).name):tx.mode==='sector'?SECTORS.find(s=>s[0]===tx.source)[1]:'Other services',signed(tx.mode==='borrow'?gap:tx.mode==='tax'?tax:cuts),tx.mode==='borrow'?'initial borrowing change':tx.mode==='tax'?'annual receipt change':'annual offset',Math.abs(gap)<1e-7?'Initial funding gap: £0bn':'Initial gap: '+signed(gap)],['03','ECONOMY','Real GDP',`${fmt((r.realGdp/b.realGdp-1)*100,2)}%`,'vs current plan',`Inflation ${fmt(r.inflation-b.inflation,2)} pp`],['04','PUBLIC FINANCES','Public debt',signed(r.debt-b.debt),'vs current plan',`Interest ${signed(r.interest-b.interest)}/yr`]];
 $('#labNodes').innerHTML=cards.map((c,n)=>`<button class="circuit-node ${n===labFocus?'selected':''}" data-stage="${n}" aria-pressed="${n===labFocus}"><span class="node-kicker"><b>${c[0]}</b>${c[1]}<span>↗</span></span><span class="node-title">${esc(c[2])}</span><strong>${c[3]}</strong><small>${c[4]}</small><span class="node-footer">${c[5]}</span></button>`).join('');
 $$('#labNodes button').forEach(btn=>{btn.onclick=()=>{labFocus=+btn.dataset.stage;drawLab();$('#labNodes [data-stage="'+labFocus+'"]').focus({preventScroll:true});};btn.onmouseenter=()=>highlightLab(+btn.dataset.stage);btn.onmouseleave=()=>highlightLab(labFocus);btn.onfocus=()=>highlightLab(+btn.dataset.stage);});highlightLab(labFocus);
 const note=LAB_NOTES[labFocus];$('#labInspector').innerHTML=`<span class="inspection-label">INSIDE STEP 0${labFocus+1}</span><h3>${note[0]}</h3><p>${note[1]}</p>${labFocus===1?`<div class="mini-equation">Spending change ${signed(sum(Object.values(tx.spend)))} − receipts ${signed(tax)} = borrowing ${signed(gap)}</div>`:labFocus===3?`<div class="mini-equation">${r.year}: opening debt ${cash(r.openingDebt)} + borrowing ${cash(r.borrowing)}${labStep===0?' · starting-year snapshot':' = '+cash(r.debt)}</div>`:''}`;
 $('#labYear').textContent=r.year;$('#labTime').value=labStep;$('#labBack').disabled=labStep===0;$('#labNext').disabled=labStep===horizon;
 $('#labSpark').innerHTML=`<div class="spark-label">Extra debt over time <b>${signed(r.debt-b.debt)}</b></div>${lineSvg(labRows.map((v,i)=>v.debt-labBase[i].debt),'#218779',400,65,r.year,labRows.map(v=>v.year)).replace('Historical series','Simulated extra debt')}`;
}
function highlightLab(n){$$('.circuit-node').forEach((el,i)=>el.classList.toggle('linked',Math.abs(i-n)<=1));$$('[data-wire]').forEach(el=>el.classList.toggle('lit',+el.dataset.wire===n||+el.dataset.wire===n-1));}
