/* Funding transactions are explicit annual changes, all in £bn. */
function fundingTransaction(d,p,id,target,mode,source){
 const amount=target-(p.spend[id]||0),spend={[id]:amount},tax={};
 const eligible=SECTORS.map(s=>s[0]).filter(k=>k!==id&&k!=='residual');
 if(!Number.isFinite(target)||target>2000)throw Error('Enter a finite spending change up to £2,000bn.');
 if(mode==='sector'){
  if(!eligible.includes(source))throw Error('Choose another service.');spend[source]=-amount;
 }else if(mode==='equal'){
  eligible.forEach(k=>spend[k]=-amount/eligible.length);
 }else if(mode==='tax'){
  const receipts=inputs(d,p).revenues;
  if(!receipts.some(t=>t.id===source&&!t.id.startsWith('custom')))throw Error('Choose an existing receipt category.');tax[source]=amount;
 }else if(mode!=='borrow')throw Error('Choose a funding route.');
 const next={...p,spend:{...p.spend},tax:{...p.tax}};
 for(const [k,v]of Object.entries(spend))next.spend[k]=(next.spend[k]||0)+v;
 for(const [k,v]of Object.entries(tax))next.tax[k]=(next.tax[k]||0)+v;
 validateFunding(d,next);
 return {next,transaction:{id,amount,mode,source,spend,tax}};
}
function validateFunding(d,p){const i=inputs(d,p);for(const [k,v]of Object.entries(i.spending))if(k!=='residual'&&v < -1e-7)throw Error(`${SECTORS.find(s=>s[0]===k)[1]} cannot fall below zero. Choose another funding route or a smaller change.`);if(i.revenues.some(t=>t.amount < Math.min(0,t.value)-1e-7))throw Error('Tax receipts cannot fall below zero. Choose a smaller reduction.');}
function fundingLines(t){return [...Object.entries(t.spend).filter(([,v])=>Math.abs(v)>1e-8).map(([k,v])=>({name:SECTORS.find(s=>s[0]===k)[1],value:v,style:v>0?'fund-add':'fund-cut',label:v>0?'Spending added':'Spending cut'})),...Object.entries(t.tax).map(([k,v])=>({name:shortName(inputs(datum(),policy).revenues.find(r=>r.id===k).name),value:v,style:'fund-tax',label:v>0?'Receipts raised':'Receipts reduced'})),...(t.mode==='borrow'&&t.amount?[{name:t.amount>0?'Additional borrowing':'Borrowing avoided',value:t.amount,style:'fund-borrow',label:'Funding gap'}]:[])];}
function fundingList(t){return fundingLines(t).map(l=>`<div class="fund-line ${l.style}"><span>${esc(l.name)}<small>${l.label}</small></span><strong>${signed(l.value)}</strong></div>`).join('');}
function renderFunding(){const el=$('#fundingLedger');const tx=policy.funding||[];el.innerHTML=tx.length?`<div class="funding-ledger"><div class="eyebrow">WHERE THE MONEY MOVES</div><p class="fine">Annual transactions · £bn. Cards show net changes from the historical budget.</p>${tx.map((t,i)=>`<details ${i===tx.length-1?'open':''}><summary>${esc(SECTORS.find(s=>s[0]===t.id)[1])} ${signed(t.amount)}</summary>${fundingList(t)}</details>`).join('')}<button id="undoFunding" class="wide">Undo last spending transaction</button></div>`:'';if($('#undoFunding'))$('#undoFunding').onclick=()=>{const t=tx.at(-1),next={...policy,spend:{...policy.spend},tax:{...policy.tax}};for(const[k,v]of Object.entries(t.spend))next.spend[k]=(next.spend[k]||0)-v;for(const[k,v]of Object.entries(t.tax))next.tax[k]=(next.tax[k]||0)-v;try{validateFunding(datum(),next);}catch(e){toast(e.message);return;}next.funding=tx.slice(0,-1);policy=next;result=null;baseline=null;render();};}
function editSpending(id,preset){
 const d=datum(),value=baseSpending(d)[id],current=policy.spend[id]||0,name=SECTORS.find(s=>s[0]===id)[1];
 if(id==='residual'){modal('<h2>Accounting reconciliation</h2><p>This bridges different data vintages. It is not a service or a source of savings.</p>');return;}
 modal(`<div class="eyebrow">SPENDING & FUNDING · ${fy(year)}</div><h2>${esc(name)}</h2><p>Choose the spending change, then where the money moves.</p><div class="big-edit" id="fundAmount"></div><label for="fundDelta">Annual change from historical budget (£bn)</label><input id="fundDelta" type="number" min="${-value}" max="2000" step="0.1" value="${preset??current}"><label for="fundMode" id="fundPrompt">Funding route</label><select id="fundMode" class="wide"><option value="borrow">Borrow / reduce borrowing</option><option value="sector">Transfer with another sector</option><option value="equal">Spread across other sectors equally</option><option value="tax">Adjust a tax receipt</option></select><div id="fundSource"></div><div id="fundPreview" aria-live="polite"></div><button id="applyFunding" class="primary wide">Apply spending & funding</button><button id="fundReset" class="wide">Set this sector to its historical budget</button>${id==='social'?'<button id="fundPension" class="wide">Pension uprating settings →</button>':''}`);
 function sources(){const mode=$('#fundMode').value;$('#fundSource').innerHTML=mode==='sector'?`<label for="fundTarget">Other sector</label><select id="fundTarget" class="wide">${SECTORS.filter(([k])=>k!==id&&k!=='residual').map(([k,n])=>`<option value="${k}">${esc(n)}</option>`).join('')}</select>`:mode==='tax'?`<label for="fundTarget">Receipt category</label><select id="fundTarget" class="wide">${inputs(d,policy).revenues.filter(t=>!t.id.startsWith('custom')).map(t=>`<option value="${t.id}">${esc(shortName(t.name))}</option>`).join('')}</select>`:'';if($('#fundTarget'))$('#fundTarget').onchange=preview;preview();}
 function proposal(){if($('#fundDelta').value.trim()==='')throw Error('Enter a spending change.');return fundingTransaction(d,policy,id,Number($('#fundDelta').value),$('#fundMode').value,$('#fundTarget')?.value);}
 function preview(){const v=Number($('#fundDelta').value);$('#fundAmount').textContent=cash(value+v);$('#fundPrompt').textContent=v-current<0?'Use the savings':'Fund the increase';try{const {next,transaction:t}=proposal();const from=simulate(d,policy,settings,horizon),to=simulate(d,next,settings,horizon),a=from.at(-1),b=to.at(-1);$('#fundPreview').innerHTML=`<p class="fine">This edit moves ${cash(Math.abs(t.amount))} per year from your current plan. Equal sharing means equal £ amounts across services, excluding debt interest and reconciliation.</p>${fundingList(t)}<div class="fund-forecast"><strong>Effect of this edit · after ${horizon} years</strong><div>Public debt <b>${signed(b.debt-a.debt)}</b></div><div>Annual debt interest <b>${signed(b.interest-a.interest)}</b></div><div>Inflation · first / final year <b>${fmt(to[1].inflation-from[1].inflation,2)} / ${fmt(b.inflation-a.inflation,2)} pp</b></div><div>Real GDP <b>${fmt((b.realGdp/a.realGdp-1)*100,2)}%</b></div></div><p class="fine">Compared with your current plan. New-debt yield stays at your ${fmt(settings.yield)}% assumption; borrowing changes interest costs, not the rate automatically. Inflation follows the model’s assumed demand response. Offsets balance initially; later tax, demographic and price effects can reopen a deficit.</p>`;$('#applyFunding').disabled=Math.abs(t.amount)<1e-8;}catch(e){$('#fundPreview').innerHTML=`<p class="fund-error" role="alert">${esc(e.message)}</p>`;$('#applyFunding').disabled=true;}}
 $('#fundDelta').oninput=preview;$('#fundMode').onchange=sources;$('#fundReset').onclick=()=>{$('#fundDelta').value=0;preview();};if($('#fundPension'))$('#fundPension').onclick=openSettings;
 $('#applyFunding').onclick=()=>{try{const {next,transaction}=proposal();next.funding=[...(policy.funding||[]),transaction];policy=next;result=null;baseline=null;render();$('#drawer').close();toast('Spending and funding applied together');}catch(e){toast(e.message);}};sources();
}
